
kafka:
  bootstrap:
    server: 127.0.0.1:9092
  producer:
    key.serializer: StringSerializer
    value.serializer: StringSerializer
  consumer:
    key.serializer: StringSerializer
    value.serializer: StringSerializer